name: Update work history data

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  Update:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: CodyCBakerPhD/historia-action@v2
        with:
          username: yarikoptic
          project-url: https://github.com/orgs/con/projects/13
          recency: "2"
          token: ${{ secrets.GH_PAT }}

      - uses: CodyCBakerPhD/historia-action/project-update-dates@v2
        with:
          url: [project url]
          recency: "2"
          token: ${{ secrets.GH_PAT }}
